export const PUSH_EVENT = 'PUSH_EVENT'
export const PUSH_STUDENT = 'PUSH_STUDENT'
export const IS_LOGGED = 'IS_LOGGED'


export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST'
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS'
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE'


export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE'
